<a href="https://colab.research.google.com/github/karthik0967/Sentiment-Analysis/blob/main/SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ipython-autotime
%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 3.89 s (started: 2021-03-16 17:13:35 +00:00)


In [ ]:
!pip install vaderSentiment

time: 3.88 s (started: 2021-03-16 17:13:43 +00:00)


In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vs=SentimentIntensityAnalyzer()

time: 34.3 ms (started: 2021-03-16 17:13:47 +00:00)


In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import os

time: 2.85 ms (started: 2021-03-16 17:13:50 +00:00)


In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/bhukyavamshirathod/Sentimental-Analysis/main/Train.csv')
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

time: 157 ms (started: 2021-03-16 17:13:54 +00:00)


In [ ]:
import nltk
nltk.download('stopwords')
stopword_list=nltk.corpus.stopwords.words('english')
negative_words=['no','not',"don't","aren't","couldn't","didn't","doesn't","hadn't","hasn't","haven't","isn't","mightn't","mustn't","needn't","shouldn't","wasn't","weren't","won't","wouldn't"]
for negative_word in negative_words:
  stopword_list.remove(negative_word)

len(stopword_list)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


160

time: 29.5 ms (started: 2021-03-16 17:16:31 +00:00)


In [ ]:
stopword_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

time: 19.7 ms (started: 2021-03-16 17:16:42 +00:00)


In [ ]:
# removing html tag
def html_tag(text):
  soup=BeautifulSoup(text,"html.parser")
  new_text=soup.get_text()
  return new_text

time: 3.55 ms (started: 2021-03-16 17:18:14 +00:00)


In [ ]:
# expand contractions
!pip install contractions
import contractions
def con(text):
  expand=contractions.fix(text)
  return expand

     |████████████████████████████████| 266kB 9.3MB/s 
     |████████████████████████████████| 327kB 36.8MB/s 
  Created wheel for pyahocorasick: filename=pyahocorasick-1.4.1-cp37-cp37m-linux_x86_64.whl size=85268 sha256=0e7fe74b346e162d636144f8761e9237114beac8a08c7b8b22488a21b3e0cca3
  Stored in directory: /root/.cache/pip/wheels/e4/ab/f7/cb39270df8f6126f3dd4c33d302357167086db460968cfc80c
Successfully built pyahocorasick
time: 8.33 s (started: 2021-03-16 17:18:26 +00:00)


In [ ]:
# removal of special character
import re
def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text

time: 5.81 ms (started: 2021-03-16 17:19:45 +00:00)


In [ ]:
# remove stop words
from nltk.tokenize.toktok import ToktokTokenizer
tokenizer=ToktokTokenizer()

def remove_stop_words(text):
  tokens=tokenizer.tokenize(text)
  tokens=[token.strip() for token in tokens]
  filtered_tokens=[token for token in tokens if token not in stopword_list]
  filtered_text=' '.join(filtered_tokens)
  return filtered_text

time: 5.92 ms (started: 2021-03-16 17:19:49 +00:00)


In [ ]:
# 1: lower case
# 2: html tag
# 3: contraction
# 4: tokenize
# 5: stop words
df.tweet=df.tweet.apply(lambda x:x.lower())
df.tweet=df.tweet.apply(html_tag)
df.tweet=df.tweet.apply(con)
df.tweet=df.tweet.apply(remove_sp)
df.tweet=df.tweet.apply(remove_stop_words)

df.head()

id  label                                              tweet
0   1      0  user father dysfunctional selfish drags kids d...
1   2      0  user user thanks lyft credit not use not offer...
2   3      0                                     bihday majesty
3   4      0                            model love take time ur
4   5      0                      factsguide society motivation

time: 1.59 s (started: 2021-03-16 17:19:58 +00:00)


In [ ]:
# df['compound']=df['news_article'].apply(lambda x: vs.polarity_scores(x)['compound'])
df['compound']=df['tweet'].apply(lambda x: vs.polarity_scores(x)['compound'])

time: 698 ms (started: 2021-03-16 17:20:10 +00:00)


In [ ]:
conditions = [
    (df['compound'] >= 0.05),
    (df['compound'] > -0.05) & (df['compound'] < 0.05),
    (df['compound'] <= -0.05)
    ]

# create a list of the values we want to assign for each condition
values = ['Positive', 'Neutral', 'Negative']

# create a new column and use np.select to assign values to it using our lists as arguments
df['tier'] = np.select(conditions, values)

# display updated DataFrame
df

id  label  ... compound      tier
0         1      0  ...  -0.7650  Negative
1         2      0  ...   0.6705  Positive
2         3      0  ...   0.0000   Neutral
3         4      0  ...   0.6369  Positive
4         5      0  ...   0.3400  Positive
...     ...    ...  ...      ...       ...
9995   9996      0  ...   0.5423  Positive
9996   9997      0  ...   0.1280  Positive
9997   9998      0  ...   0.4215  Positive
9998   9999      0  ...  -0.7096  Negative
9999  10000      0  ...   0.5994  Positive

[10000 rows x 5 columns]

time: 107 ms (started: 2021-03-16 17:20:18 +00:00)


In [ ]:
df.head()

id  label  ... compound      tier
0   1      0  ...  -0.7650  Negative
1   2      0  ...   0.6705  Positive
2   3      0  ...   0.0000   Neutral
3   4      0  ...   0.6369  Positive
4   5      0  ...   0.3400  Positive

[5 rows x 5 columns]

time: 23.9 ms (started: 2021-03-16 17:20:24 +00:00)


In [ ]:
x = df.iloc[:,2].values
y = df.iloc[:,-1].values

time: 2.5 ms (started: 2021-03-16 17:20:29 +00:00)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0,stratify = y)
x_train.shape

(7000,)

time: 34.7 ms (started: 2021-03-16 17:20:33 +00:00)


In [ ]:
np.unique(y_train,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([1460, 1903, 3637]))

time: 21.3 ms (started: 2021-03-16 17:20:59 +00:00)


In [ ]:
np.unique(y_test,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 626,  816, 1558]))

time: 22.2 ms (started: 2021-03-16 17:21:07 +00:00)


In [ ]:
# Pipeline = Combine above 2 steps
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
# Syntax : Pipeline([('Variable 1',Method 1()),('Variable 2',Method 2())])

time: 6.79 ms (started: 2021-03-16 17:28:06 +00:00)


In [ ]:
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC(C=1.6,kernel='linear'))])

time: 1.98 ms (started: 2021-03-16 17:47:07 +00:00)


In [ ]:
text_model.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 SVC(C=1.6, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', d

time: 6.1 s (started: 2021-03-16 17:47:11 +00:00)


In [ ]:
y_pred = text_model.predict(x_test)
y_pred

array(['Positive', 'Positive', 'Neutral', ..., 'Negative', 'Positive',
       'Neutral'], dtype=object)

time: 1.28 s (started: 2021-03-16 17:45:37 +00:00)


In [ ]:
np.unique(y_pred,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 574,  856, 1570]))

time: 28.8 ms (started: 2021-03-16 17:40:59 +00:00)


In [ ]:
y_test

array(['Positive', 'Neutral', 'Neutral', ..., 'Negative', 'Positive',
       'Neutral'], dtype=object)

time: 14.8 ms (started: 2021-03-16 17:39:49 +00:00)


In [ ]:
# Evaluation
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

time: 8.36 ms (started: 2021-03-16 17:47:22 +00:00)


In [ ]:
accuracy_score(y_pred,y_test)*100

79.60000000000001

time: 17 ms (started: 2021-03-16 17:47:24 +00:00)


In [ ]:
confusion_matrix(y_pred,y_test)

array([[ 313,   30,   59],
       [ 121,  569,  109],
       [ 192,  217, 1390]])

time: 26.2 ms (started: 2021-03-16 17:29:14 +00:00)


In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

    Negative       0.50      0.78      0.61       402
     Neutral       0.70      0.71      0.70       799
    Positive       0.89      0.77      0.83      1799

    accuracy                           0.76      3000
   macro avg       0.70      0.75      0.71      3000
weighted avg       0.79      0.76      0.77      3000

time: 129 ms (started: 2021-03-16 17:29:18 +00:00)


In [ ]:
text_model.predict(["#people aren't protesting #trump because a #republican not every on e won never hw is dumbo kjkjwe @#$%^&*€¦ "])

array(['Positive'], dtype=object)

time: 23 ms (started: 2021-03-16 17:22:59 +00:00)


In [ ]:
!pip install streamlit
!pip install pyngrok==4.1.1
from pyngrok import ngrok

     |████████████████████████████████| 7.5MB 7.9MB/s 
     |████████████████████████████████| 163kB 39.9MB/s 
     |████████████████████████████████| 81kB 5.5MB/s 
     |████████████████████████████████| 112kB 40.4MB/s 
     |████████████████████████████████| 4.6MB 27.4MB/s 
     |████████████████████████████████| 71kB 5.3MB/s 
     |████████████████████████████████| 122kB 34.3MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13448 sha256=368c2e99ab1aa4b77427f1ea3c2b4d983d7e3358ec97e0c346fc428483c7d29c
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.0 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


  Created wheel for pyngrok: filename=pyngrok-4.1.1-cp37-none-any.whl size=15971 sha256=3408192ea49edefc3658da35ed205ebdaba051453ba099c33a31d4e3f9c0ab34
  Stored in directory: /root/.cache/pip/wheels/97/71/0d/1695f7c8815c0beb3b5d9b35d6eec9243c87e6070fbe3977fa
Successfully built pyngrok
time: 23 s (started: 2021-03-16 17:23:03 +00:00)


In [ ]:
%%writefile app.py
import streamlit as st
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import os

import nltk
nltk.download('stopwords')
stopword_list=nltk.corpus.stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('not')

# remove html tag
def html_tag(text):
  soup=BeautifulSoup(text,"html.parser")
  new_text=soup.get_text()
  return new_text

# !pip install contractions
import contractions
def con(text):
  expand=contractions.fix(text)
  return expand

# removal of special character
import re
def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text


# remove stop words
from nltk.tokenize.toktok import ToktokTokenizer
tokenizer=ToktokTokenizer()

def remove_stop_words(text):
  tokens=tokenizer.tokenize(text)
  tokens=[token.strip() for token in tokens]
  filtered_tokens=[token for token in tokens if token not in stopword_list]
  filtered_text=' '.join(filtered_tokens)
  return filtered_text


st.title("Tweet's Sentiment Analysis")

df = pd.read_csv('https://raw.githubusercontent.com/bhukyavamshirathod/Sentimental-Analysis/main/Train.csv')

df.tweet=df.tweet.apply(lambda x:x.lower())
df.tweet=df.tweet.apply(html_tag)
df.tweet=df.tweet.apply(con)
df.tweet=df.tweet.apply(remove_sp)
df.tweet=df.tweet.apply(remove_stop_words)

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vs=SentimentIntensityAnalyzer()

df['compound']=df['tweet'].apply(lambda x: vs.polarity_scores(x)['compound'])

conditions = [
    (df['compound'] >= 0.05),
    (df['compound'] > -0.05) & (df['compound'] < 0.05),
    (df['compound'] <= -0.05)
    ]

# create a list of the values we want to assign for each condition
values = ['Positive', 'Neutral', 'Negative']

# create a new column and use np.select to assign values to it using our lists as arguments
df['tier'] = np.select(conditions, values)

x = df.iloc[:,2].values
y = df.iloc[:,-1].values

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x,y)
select = st.text_input('Enter your message')

if(st.markdown(
    '<span class="badge badge-pill badge-success"> Badge </span>',
    unsafe_allow_html=True
)):
  op = text_model.predict([select])
  ans=op[0]

  if ans == 'Positive':
    st.success("Positive 🙂")
  if ans == 'Negative':
    st.error("Negative 😠")
  if ans== 'Neutral':
    st.warning("Neutral 😐")

Overwriting app.py
time: 8.21 ms (started: 2021-03-16 17:23:56 +00:00)


In [ ]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://414443590712.ngrok.io'

time: 2.27 s (started: 2021-03-16 17:24:00 +00:00)
